dotCMS/core#19353 Create new logout page for SAML
dotCMS/core-web pull request #1447
Opened 2020-10-01 16:47 UTC by hmoreras

2020-10-01 16:48 UTC, hmoreras commented on src/app/api/services/dot-router/dot-router.service.ts
> +        if (parameters) {
Still need to double check if this is needed.

2020-10-02 20:40 UTC, fmontes requested changes

2020-10-02 20:40 UTC, fmontes commented on src/app/api/services/dot-router/dot-router.service.spec.ts
> +            jasmine.clock().install();
😯 didn't know this.

2020-10-02 20:40 UTC, fmontes commented on src/app/view/components/_common/iframe/iframe-component/iframe.component.spec.ts
>  import { RouterTestingModule } from '@angular/router/testing';
What happen here?

2020-10-02 20:40 UTC, fmontes commented on src/app/view/components/_common/iframe/iframe-component/iframe.component.ts
> +               window.location.href = '/dotAdmin/logout';
can we test this?

2020-10-02 20:40 UTC, fmontes commented on src/app/view/components/dot-toolbar/components/dot-my-account/dot-my-account.component.ts
> +                    window.location.href = '/dotAdmin/logout';
Should we do this in the router service?

2020-10-05 16:35 UTC, alfredo-dotcms commented on src/app/api/services/dot-router/dot-router.service.spec.ts
> +        async(() => {
remove

2020-10-05 16:36 UTC, alfredo-dotcms commented on src/app/api/services/dot-router/dot-router.service.spec.ts
> +            jasmine.clock().install();
what's that for?

2020-10-05 16:38 UTC, alfredo-dotcms commented on src/app/view/components/dot-toolbar/components/dot-my-account/dot-my-account.component.spec.ts
>          const changePassword = de.query(By.css('#dot-my-account-change-password-option'));
migrate this to `TestBed`

2020-10-05 16:41 UTC, alfredo-dotcms commented on src/app/view/components/login/forgot-password-component/forgot-password.component.ts
>       * @memberof ForgotPasswordComponent
update doc

2020-10-05 16:42 UTC, alfredo-dotcms commented on src/app/api/services/dot-router/dot-router.service.ts
> +    goToLogin(navExtras?: NavigationExtras): void {
doc?

2020-10-05 21:03 UTC, hmoreras commented on src/app/api/services/dot-router/dot-router.service.spec.ts
> +            jasmine.clock().install();
to mock the value of `new Date()`

2020-10-09 18:59 UTC, merged