dotCMS/core#19088 Add advanced template and fix unit tests and messages keys
dotCMS/core-web pull request #1516
Opened 2020-11-18 23:17 UTC by fmontes

2020-11-23 22:54 UTC, ivorpad approved these changes

2020-11-24 15:02 UTC, hmoreras commented on src/app/portlets/dot-templates/dot-template-create-edit/dot-template-builder/dot-template-builder.component.html
> +    <p-tabPanel [header]="item.type === 'advanced' ? 'Code' : 'Design'">
missing message key

2020-11-24 15:17 UTC, hmoreras requested changes

2020-11-24 15:17 UTC, hmoreras commented on src/app/portlets/dot-templates/dot-template-create-edit/dot-template-builder/dot-template-builder.component.html
> +    <p-tabPanel [header]="item.type === 'advanced' ? 'Code' : 'Design'">
missing messages keys in all file

2020-11-24 15:17 UTC, hmoreras commented on src/app/portlets/dot-templates/dot-template-create-edit/resolvers/dot-template-create-edit.resolver.spec.ts
> +    it('should be created', (done) => {
better description

2020-11-25 19:47 UTC, hmoreras approved these changes

2020-11-25 20:02 UTC, merged