issue-19597-add-route-to-create-new-content-type
dotCMS/core-web pull request #1538
Opened 2020-12-14 15:36 UTC by alfredo-dotcms

2020-12-15 16:26 UTC, fmontes requested changes

2020-12-15 16:26 UTC, fmontes commented on src/app/app-routing.module.ts
> +                                component: DotCreateContentletComponent,
This should be a lazy load module.

2020-12-16 14:12 UTC, fmontes requested changes

2020-12-16 14:12 UTC, fmontes commented on src/app/api/services/dot-router/dot-router.service.spec.ts
> +
This test is not right you are only testing that you called the method but not what happen inside the method, what you need to assert here is that when you call those methods the `this.router.navigate` was called with the specific url like this one: https://github.com/dotCMS/core-web/blob/9b20c831fda4c8d10e9083b3001f6325afce5fd5/src/app/api/services/dot-router/dot-router.service.spec.ts#L113

2021-01-05 14:34 UTC, hmoreras approved these changes

2021-01-14 15:08 UTC, fmontes approved these changes

2021-01-14 15:32 UTC, merged