dotCMS/core#19701 Add the "don't show again" checkbox
dotCMS/core-web pull request #1539
Opened 2020-12-15 18:06 UTC by hmoreras

- Add Checkbox

2020-12-15 20:30 UTC, fmontes requested changes

2020-12-15 20:30 UTC, fmontes commented on src/app/api/services/dot-starter/dot-starter.service.ts
> +export class DotStarterService {
```suggestion
export class DotToolGroupStarterService {
```

Right now it looks like a service to handle "starters" and is not that.

Don't forget file names.

2020-12-15 20:30 UTC, fmontes commented on src/app/api/services/dot-starter/dot-starter.service.ts
> +    hide(): any {
doc and type

2020-12-15 20:30 UTC, fmontes commented on src/app/api/services/dot-starter/dot-starter.service.ts
> +    show(): any {
doc and type

2020-12-15 20:30 UTC, fmontes commented on src/app/portlets/dot-starter/dot-starter.component.ts
> +        console.log(hide);
remove

2020-12-15 20:30 UTC, fmontes commented on src/app/portlets/dot-starter/dot-starter.component.ts
> +    handleVisibility(hide: boolean): void {
doc.

2020-12-16 00:12 UTC, alfredo-dotcms commented on src/app/api/services/dot-tool-group/dot-tool-group.service.spec.ts
> +    });
you are missing
``` afterEach(() => {
        httpMock.verify();
    });```

2020-12-16 14:08 UTC, fmontes approved these changes

2020-12-16 15:45 UTC, merged