dotCMS/core#19087 internal QA feedback
dotCMS/core-web pull request #1550
Opened 2021-01-14 21:05 UTC by hmoreras

- Save template properties should not redirect to listing
- Route not reloading when url params change, in general, but specific in edit template by inode.

2021-01-14 22:19 UTC, alfredo-dotcms approved these changes

2021-01-15 00:28 UTC, fmontes requested changes

2021-01-15 00:34 UTC, fmontes commented on src/app/api/services/dot-router/dot-router.service.ts
> +        };
We can't do this globally, it makes our app slow, we need to be clever and implement the method for just the routes we want:

```
shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        console.log("deciding to reuse", "future", future.routeConfig, "current", curr.routeConfig, "return: ", future.routeConfig === curr.routeConfig);
        return future.routeConfig === curr.routeConfig;
    }
```

more info: https://stackoverflow.com/questions/41280471/how-to-implement-routereusestrategy-shoulddetach-for-specific-routes-in-angular

2021-01-19 14:08 UTC, fmontes approved these changes

2021-01-19 14:19 UTC, merged