dotCMS/core#19798 add-show-starter-on-my-account-dialog
dotCMS/core-web pull request #1552
Opened 2021-01-15 23:46 UTC by alfredo-dotcms

2021-01-19 14:03 UTC, fmontes requested changes

2021-01-19 14:03 UTC, fmontes commented on src/app/view/components/dot-toolbar/components/dot-my-account/dot-my-account.component.spec.ts
> +        expect(accountService.addStarterPage).toHaveBeenCalledTimes(1);
You are not testing the change event you add to the html. That's is the tests not changing the `showStarter` manually.

2021-01-19 14:03 UTC, fmontes commented on src/app/view/components/dot-toolbar/components/dot-my-account/dot-my-account.component.ts
> +                this.showStarter = showStarter;
Perfect candidate for `async` pipe.

2021-01-19 14:03 UTC, fmontes commented on src/app/view/components/dot-toolbar/components/dot-my-account/dot-my-account.component.ts
> +    toggleShowStarter(): void {
Needs doc.

2021-01-20 14:46 UTC, fmontes requested changes

2021-01-20 14:46 UTC, fmontes commented on src/app/view/components/dot-toolbar/components/dot-my-account/dot-my-account.component.spec.ts
> +        const showStarter = de.query(By.css('#dot-my-account-show-starter'));
testId?

2021-01-20 15:43 UTC, fmontes approved these changes

2021-01-22 18:24 UTC, hmoreras approved these changes

2021-01-22 19:19 UTC, merged