Added dot-portlet-box in content types to frame the iframes
dotCMS/core-web pull request #1557
Opened 2021-01-20 23:18 UTC by ivorpad

Fixed the issue reported in https://github.com/dotCMS/core/issues/19824

2021-01-20 23:20 UTC, ivorpad commented on src/app/portlets/shared/dot-content-types-edit/components/fields/content-type-fields-row/content-type-fields-row.component.scss
> -    border-radius: $border-radius;
To maintain consistency with `dot-portlet-box`

2021-01-20 23:21 UTC, ivorpad commented on src/app/portlets/shared/dot-content-types-edit/components/layout/content-types-layout.component.html
> +            <dot-portlet-box class="content-type__fields-main">
As per DMs on Slack, I don't think it's necessary to refactor this component as there might be too many edge cases. I decided to target with a CSS class instead.

2021-01-21 12:58 UTC, fmontes requested changes

2021-01-21 12:58 UTC, fmontes commented on src/app/portlets/shared/dot-content-types-edit/components/layout/content-types-layout.component.html
>          <div class="content-type__fields-layout" id="content-type-form-layout">
Can we get rid of this `div` in favor of just `dot-portlet-box`?

2021-01-21 12:58 UTC, fmontes commented on src/app/portlets/shared/dot-content-types-edit/components/layout/content-types-layout.component.html
>          header="{{ 'contenttypes.tab.fields.header' | dm }}"
All the new `dot-portlet-box` needs tests.

2021-02-12 17:22 UTC, alfredo-dotcms submitted a review, later dismissed

2021-02-12 18:11 UTC, hmoreras approved these changes

2021-02-19 18:38 UTC, merged