Issue 19802 add descriptions and link to starter page
dotCMS/core-web pull request #1558
Opened 2021-01-21 16:40 UTC by alfredo-dotcms

2021-01-21 19:13 UTC, hmoreras approved these changes

2021-01-22 17:44 UTC, fmontes requested changes

2021-01-22 17:44 UTC, fmontes commented on src/app/portlets/dot-starter/dot-starter.component.html
> +                        href="javascript:void(0)"
To navigate in a `<a>` we should use https://angular.io/api/router/RouterLink

2021-01-22 17:44 UTC, fmontes commented on src/app/portlets/dot-starter/dot-starter.component.ts
> +    };
Directly in the hmt routerLink

2021-01-22 17:44 UTC, fmontes commented on src/app/portlets/dot-starter/dot-starter.component.html
> +            data-testid="starter.footer.link.community"
Isn't should this be camelCase? we need to doc this thing we keep having this issues.

2021-01-22 17:44 UTC, fmontes commented on src/app/portlets/dot-starter/dot-starter.component.scss
> +        min-height: 97px;
px? why?

2021-01-22 17:44 UTC, fmontes commented on src/app/portlets/dot-starter/dot-starter.component.scss
> +        margin-right: 2rem;
spacing?

2021-01-22 22:03 UTC, fmontes approved these changes

2021-01-25 15:33 UTC, merged