dotCMS/core#19840 Reload the template portlet when user change the site in the top-right selector
dotCMS/core-web pull request #1561
Opened 2021-01-22 20:43 UTC by fmontes

…

2021-01-22 21:55 UTC, hmoreras requested changes

2021-01-22 21:55 UTC, hmoreras commented on src/app/app-routing.module.ts
> +            onSameUrlNavigation: 'reload'
is this needed ?

2021-01-22 21:55 UTC, hmoreras commented on src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.ts
> +                this.dotRouterService.gotoPortlet('templates');
implements a reload,  looks like this might work, https://stackoverflow.com/a/58114797/3847132

2021-01-25 13:57 UTC, ivorpad approved these changes

2021-01-25 16:29 UTC, hmoreras approved these changes

2021-01-25 16:29 UTC, merged