#19849 Added site host theme selector
dotCMS/core-web pull request #1563
Opened 2021-01-25 17:24 UTC by ivorpad

2021-01-25 23:11 UTC, fmontes requested changes

2021-01-25 23:11 UTC, fmontes commented on src/app/view/components/dot-theme-selector-dropdown/dot-theme-selector-dropdown.component.html
> +    <div class="searchable-dropdown__search">
Please renamed this classes to the context this html live now.

2021-01-25 23:11 UTC, fmontes commented on src/app/view/components/dot-theme-selector-dropdown/dot-theme-selector-dropdown.component.scss
> +            .site-selector__title {
Please add a comment here lilke: "This is to style as disabled textfield the label when there is only one site"

2021-01-27 18:06 UTC, hmoreras requested changes

2021-01-27 18:06 UTC, hmoreras commented on src/app/view/components/dot-theme-selector-dropdown/dot-theme-selector-dropdown.component.ts
>                  this.themes = themes;
with this, we might have the same problem of the container selector, that the page do not refresh on pagination.

2021-01-28 20:22 UTC, merged