dotCMS/core#19987 Fixing bug
dotCMS/core-web pull request #1593
Opened 2021-02-23 17:54 UTC by freddyucv

2021-02-23 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1593) it.</sub>

2021-02-23 18:06 UTC, fmontes requested changes

2021-02-23 18:06 UTC, fmontes commented on src/app/portlets/shared/dot-content-types-edit/components/fields/content-type-fields-drop-zone/content-type-fields-drop-zone.component.html
> +    <p-tabView (onChange)="handleTabChange($event.index)">
Why this fix it?

2021-02-23 18:06 UTC, fmontes commented on src/app/portlets/shared/dot-content-types-edit/components/fields/content-type-fields-drop-zone/content-type-fields-drop-zone.component.spec.ts
> +    fit('should have propertiesForm', () => {
Remove fit.

2021-02-23 19:48 UTC, alfredo-dotcms approved these changes

2021-02-23 21:32 UTC, fmontes requested changes

2021-02-23 21:32 UTC, fmontes commented on src/app/portlets/shared/dot-content-types-edit/components/fields/content-type-fields-drop-zone/content-type-fields-drop-zone.component.html
> +    <p-tabView [(activeIndex)]="activeTab" (onChange)="handleTabChange($event.index)">
needs testing.

2021-02-23 22:33 UTC, freddyucv commented on src/app/portlets/shared/dot-content-types-edit/components/fields/content-type-fields-drop-zone/content-type-fields-drop-zone.component.html
> +    <p-tabView [(activeIndex)]="activeTab" (onChange)="handleTabChange($event.index)">
done

2021-02-23 22:33 UTC, freddyucv commented on src/app/portlets/shared/dot-content-types-edit/components/fields/content-type-fields-drop-zone/content-type-fields-drop-zone.component.html
> +    <p-tabView (onChange)="handleTabChange($event.index)">
done

2021-02-24 15:23 UTC, fmontes approved these changes

2021-03-03 19:17 UTC, merged