dotCMS/core#20132 Create image editor in angular
dotCMS/core-web pull request #1639
Opened 2021-03-26 22:39 UTC by rjvelazco

I was working on building the url.

2021-03-26 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1639) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1639) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1639) it.</sub>

2021-03-26 23:03 UTC, fmontes requested changes

2021-03-26 23:03 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/dot-image-editor/components/edit-controls/edit-controls.component.html
> +    <input [(ngModel)]="params.quality"
PrimeNG have a range component: http://primefaces.org/primeng/showcase/#/slider

2021-03-26 23:03 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/dot-image-editor/components/edit-controls/edit-controls.component.ts
> +export class EditControlsComponent implements OnInit {
All the classes in the all are prefixed with `Dot`

```suggestion
export class DotEditControlsComponent implements OnInit {
```

2021-03-26 23:03 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/dot-image-editor/store-image.service.ts
> +export class StoreImageService extends ComponentStore<EditorState> {
```suggestion
export class DotStoreImageService extends ComponentStore<EditorState> {
```

2021-03-29 14:44 UTC, ivorpad approved these changes

2021-05-18 14:05 UTC, closed without merging