dotCMS/core#20157 fix cutting and pasting into the dot-material-icons…
dotCMS/core-web pull request #1641
Opened 2021-03-30 18:17 UTC by alfredo-dotcms

… component not updating value

2021-04-05 12:42 UTC, fmontes requested changes

2021-04-05 12:42 UTC, fmontes commented on libs/dotcms-webcomponents/src/elements/dot-material-icon-picker/dot-material-icon-picker.tsx
> +        const value = (e.target as any).value;
ins't this like a `HTMLInputElement` or something like that?

2021-04-05 12:42 UTC, fmontes commented on libs/dotcms-webcomponents/src/elements/dot-material-icon-picker/dot-material-icon-picker.tsx
> +        const value = (e.target as any).value;
Does this needs test update?

2021-04-07 16:17 UTC, fmontes approved these changes

2021-04-07 16:49 UTC, hmoreras approved these changes

2021-04-08 16:37 UTC, closed without merging