dotCMS/core#20433 fix
dotCMS/core-web pull request #1674
Opened 2021-05-27 22:29 UTC by alfredo-dotcms

### Proposed Changes
* After change the component, now we are not listing the selected environments when you try to push something, you need to click in the drop down to see the environments selected. When we open the push modal we are just displaying a Select Environment text and you need to click here to see the list

We need to avoid that extra click, and list the ones that was previously selected in the same component

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
![image](https://user-images.githubusercontent.com/37185433/119905085-c58e1a00-bf08-11eb-8e3f-9dfdd1211d9c.png)

2021-05-27 23:15 UTC, ivorpad submitted a review, later dismissed

2021-05-27 23:52 UTC, hmoreras submitted a review, later dismissed

2021-05-28 11:24 UTC, fmontes requested changes

2021-05-28 11:24 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/_common/dot-push-publish-env-selector/dot-push-publish-env-selector.component.ts
> +            this.pushEnvironments = environments;
Do we need a take until now?

2021-06-01 15:37 UTC, alfredo-dotcms commented on apps/dotcms-ui/src/app/view/components/_common/dot-push-publish-env-selector/dot-push-publish-env-selector.component.ts
> +            this.pushEnvironments = environments;
done! @fmontes

2021-06-02 16:09 UTC, fmontes approved these changes

2021-06-03 15:32 UTC, hmoreras approved these changes

2021-06-03 15:34 UTC, merged