Issue 20153 rules showing incomplete components and order
dotCMS/core-web pull request #1678
Opened 2021-06-16 22:20 UTC by alfredo-dotcms

### Proposed Changes
* a condition value for a session attribute is not possible
* do not deactivate the rule unless the rule is invalid
* browser conditionlet is out of order
* Logger must be deactivated in Prod
* Visitor's country not keeping the label once saved (shows the value)
* style miss-aligned rules controls 

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
DOTCMS v3 (expected)
![image](https://user-images.githubusercontent.com/37185433/122301890-90993580-cebe-11eb-86d6-8bb3a1532e7f.png)

2021-06-16 22:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1678) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1678) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1678) it.</sub>

2021-06-16 22:22 UTC, alfredo-dotcms commented
this is how it looks, after fixes
![image](https://user-images.githubusercontent.com/37185433/122302181-fab1da80-cebe-11eb-8c1a-83b7ab2f4eef.png)

2021-06-16 22:30 UTC, alfredo-dotcms commented
DEMO - current

![image](https://user-images.githubusercontent.com/37185433/122303055-2ed9cb00-cec0-11eb-97c8-fcce5e456ac9.png)

2021-06-17 14:15 UTC, fmontes requested changes

2021-06-17 14:15 UTC, fmontes commented on libs/dot-rules/src/lib/components/dot-autocomplete-tags/dot-autocomplete-tags.component.css
> +.cw-rule-actions :host ::ng-deep p-autocomplete span.p-autocomplete-multiple{
What fixes this?

2021-06-17 14:15 UTC, fmontes commented on libs/dot-rules/src/lib/condition-types/serverside-condition/serverside-condition.ts
> +            if (this._inputs.length <= 2 && change.componentInstance.currentValue instanceof ConditionModel) {
Can you extract this condition to a function with a more understandable name?

2021-06-17 14:15 UTC, fmontes commented on libs/dotcms-js/src/lib/core/logger.service.ts
> +import { environment } from '../../../../../apps/dotcms-ui/src/environments/environment';
https://nx.dev/latest/react/guides/environment-variables

2021-06-17 14:26 UTC, alfredo-dotcms commented on libs/dot-rules/src/lib/components/dropdown/dropdown.ts
> -            [editable]="allowAdditions"
`p-dropdown` is used in `cw-input-dropdown` only in dot-rules, and I looked through all places in rules and no one uses the editable option in `cw-input-dropdown`

2021-06-17 14:29 UTC, alfredo-dotcms commented on libs/dot-rules/src/lib/services/Condition.ts
> +    static fromServerConditionTransformFn(condition: ICondition, showLogs = false): ConditionModel {
at this moment and due to the task scope this is a workaround, a new task can be created later to implement a logger service that can be used through the whole app.

so @fmontes  do you suggest to keep this change or leave it as it was before?

2021-06-17 20:57 UTC, hmoreras approved these changes

2021-06-21 14:18 UTC, alfredo-dotcms commented on libs/dot-rules/src/lib/services/Condition.ts
> +    static fromServerConditionTransformFn(condition: ICondition, showLogs = false): ConditionModel {
@fmontes Logger changes reverted!

2021-06-21 17:03 UTC, fmontes approved these changes

2021-06-22 14:13 UTC, merged