dotCMS/core#19912 Update <dot-copy-button /> button component UI
dotCMS/core-web pull request #1722
Opened 2021-08-06 18:21 UTC by rjvelazco

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2021-08-06 18:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1722) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1722) it.</sub>

2021-08-06 18:48 UTC, alfredo-dotcms commented on apps/dotcms-ui/src/app/view/components/dot-copy-button/dot-copy-button.component.ts
> +    @Input() label: string = 'Copy';
mmm, `i18n` ?

2021-08-06 18:49 UTC, alfredo-dotcms commented on apps/dotcms-ui/src/app/view/components/dot-copy-button/dot-copy-button.component.scss
> +    border-radius: 2px;
`--border-radius` ?

2021-08-09 18:14 UTC, fmontes requested changes

2021-08-09 18:14 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/dot-copy-button/dot-copy-button.component.html
>  <span
This should be a `<button>`

2021-08-09 19:13 UTC, alfredo-dotcms approved these changes

2021-08-10 13:58 UTC, fmontes approved these changes

2021-08-10 18:36 UTC, merged