Issue 19784 replace momentjs for date fns
dotCMS/core-web pull request #1741
Opened 2021-08-25 22:36 UTC by alfredo-dotcms

### Proposed Changes
Moment.js has been deprecated and this library has been known for its huge size, we need to replace it with date-fns which is smaller and tree-shakeable.

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2021-09-01 17:54 UTC, fmontes approved these changes

2021-09-08 15:59 UTC, fmontes requested changes

2021-09-08 15:59 UTC, fmontes commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/content/dot-edit-content.component.spec.ts
> +                DotFormatDateService,
Don't need it.

2021-09-08 16:47 UTC, alfredo-dotcms commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/content/dot-edit-content.component.spec.ts
> +                DotFormatDateService,
@fmontes done!

2021-09-08 16:59 UTC, fmontes approved these changes

2021-09-08 17:04 UTC, merged