dotCMS/core#1738 fix rules-allowing-tags-with-only-blank-spaces
dotCMS/core-web pull request #1747
Opened 2021-09-01 16:45 UTC by alfredo-dotcms

### Proposed Changes
you can still add empty tags with blank spaces

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2021-09-01 16:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1747) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1747) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1747) it.</sub>

2021-09-01 17:38 UTC, fmontes requested changes

2021-09-01 17:38 UTC, fmontes commented on libs/dot-rules/src/lib/components/dot-autocomplete-tags/dot-autocomplete-tags.component.ts
> +        if (event.keyCode === 13 && event.currentTarget.value.trim()) {
Don't we need to do something like `!== ''`?

2021-09-01 17:59 UTC, hmoreras approved these changes

2021-09-07 19:24 UTC, fmontes approved these changes

2021-09-07 19:24 UTC, fmontes commented on libs/dot-rules/src/lib/components/dot-autocomplete-tags/dot-autocomplete-tags.component.ts
> +        if (event.keyCode === 13 && event.currentTarget.value.trim()) {
```javascript
!!("".trim())
false
```

2021-09-08 15:46 UTC, merged