√
dotCMS/core-web pull request #1793
Opened 2021-11-08 18:26 UTC by rjvelazco

2021-11-08 18:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1793) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1793) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1793) it.</sub>

2021-11-15 18:24 UTC, fmontes approved these changes

2021-11-18 19:53 UTC, hmoreras approved these changes

2021-11-18 22:54 UTC, fmontes requested changes

2021-11-18 22:54 UTC, fmontes commented on libs/block-editor/src/lib/extensions/components/bubble-menu-button/bubble-menu-button.component.scss
> +    }
Use vars, we can.

2021-11-18 22:54 UTC, fmontes commented on libs/block-editor/src/lib/extensions/components/bubble-menu/bubble-menu.component.scss
> +    }
Use vars.

2021-11-18 22:54 UTC, fmontes commented on libs/block-editor/src/lib/extensions/components/bubble-menu-button/bubble-menu-button.component.scss
> +    border-radius: 4px;
Use rems

2021-11-19 17:18 UTC, merged