dotCMS/core#21418 fix Need to refresh the site selector value after archive current site
dotCMS/core-web pull request #1822
Opened 2021-12-20 23:09 UTC by alfredo-dotcms

If you have an instance with just two sites, and select someone in the site selector and then archive the selected one, we are just leaving the selected site and you can't change this value. And the selected site is archived.

We need to update this value and leave the other one selected.

![image](https://user-images.githubusercontent.com/37185433/146844616-68b05aef-7ae1-4d20-8f4f-24a1e7a8e855.png)

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2021-12-20 23:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1822) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1822) it.</sub>

2021-12-21 13:31 UTC, fmontes requested changes

2021-12-21 13:31 UTC, fmontes commented on libs/dotcms-js/src/lib/core/site.service.ts
> +                });
Does this need a take1?

2021-12-21 16:46 UTC, fmontes approved these changes

2021-12-21 21:19 UTC, hmoreras requested changes

2021-12-21 21:19 UTC, hmoreras commented on libs/dotcms-js/src/lib/core/site.service.ts
> +            } else if (name === 'ARCHIVE_SITE') {
ternary operator

2021-12-22 16:53 UTC, hmoreras approved these changes

2021-12-22 17:00 UTC, fmontes approved these changes

2022-01-03 14:34 UTC, fmontes approved these changes

2022-01-04 14:07 UTC, merged