dotCMS/core#21414 fix add COMPARE button to Task Detail
dotCMS/core-web pull request #1843
Opened 2022-01-14 22:31 UTC by alfredo-dotcms

### Proposed Changes
We need to add the "Compare contentlet" functionality we added in History in Task Detail as well.

- label of the button should be Compare to previous versions
- in the compare dialog, the dropdown that contains version dates must show relative dates if changes were made before a week, otherwise show the standard datetime. Also make it 20px wider and add the author who did the change
- in the compare dialog change the DIFF/PLAIN switch button to img attached

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-01-14 22:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1843) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1843) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1843) it.</sub>

2022-01-19 14:27 UTC, fmontes requested changes

2022-01-19 14:27 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/dot-content-compare/components/dot-content-compare-table/dot-content-compare-table.component.html
> +                            {{ transformVersionItemLabel(selected) }}
https://medium.com/showpad-engineering/why-you-should-never-use-function-calls-in-angular-template-expressions-e1a50f9c0496

2022-01-19 14:27 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/dot-content-compare/components/dot-content-compare-table/dot-content-compare-table.component.html
> +                                : showDiff
Can we move all this logic to the pipe?

2022-01-19 14:27 UTC, fmontes commented on apps/dotcms-ui/src/app/view/components/dot-content-compare/components/dot-content-compare-table/dot-content-compare-table.component.ts
> +    transformVersionItemLabel(item: DotCMSContentlet): string {
This method is doing too much.

I propose one to transform the date and one to get the label.

2022-01-19 20:29 UTC, hmoreras approved these changes

2022-01-19 20:45 UTC, fmontes approved these changes

2022-01-19 21:10 UTC, hmoreras approved these changes

2022-01-19 22:10 UTC, merged