Add State Management to palette #21507
dotCMS/core-web pull request #1856
Opened 2022-01-25 18:11 UTC by alfredo-dotcms

### Proposed Changes
 we need to add State Management to our Content Reuse Palette

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-01-25 18:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1856) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1856) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1856) it.</sub>

2022-01-25 21:03 UTC, rjvelazco submitted a review, later dismissed

2022-01-26 20:07 UTC, hmoreras requested changes

2022-01-26 20:07 UTC, hmoreras commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/components/dot-palette/store/dot-palette.store.ts
> +    readonly languageId = this.updater((state: DotPaletteState, data: string) => {
updateLanguage or `setLanguageId`

2022-01-26 20:07 UTC, hmoreras commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/components/dot-palette/store/dot-palette.store.ts
> +    readonly viewContentlet = this.updater((state: DotPaletteState, data: string) => {
`set...`

2022-01-27 16:30 UTC, fmontes requested changes

2022-01-27 16:30 UTC, fmontes commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/components/dot-palette/dot-palette.component.ts
> +        this.store.loadContentlets(variableName);
```suggestion
        this.store.switchView(...);
```

And do all the other things internally? We only call all those here.

2022-01-27 16:30 UTC, fmontes commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/components/dot-palette/store/dot-palette.store.ts
> +    );
Remove all the selectors that are not being used and just use the full state object if you want to skip lang id cool, but I would just send it.

2022-01-28 16:15 UTC, fmontes approved these changes

2022-01-28 16:44 UTC, hmoreras approved these changes

2022-02-01 19:30 UTC, merged