dotCMS/core#21552 Add forms from content palette error
dotCMS/core-web pull request #1868
Opened 2022-02-03 20:59 UTC by hmoreras

### Proposed Changes
* add forms on drop correctly. 

### Checklist
- [x ] Tests

2022-02-03 20:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1868) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1868) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1868) it.</sub>

2022-02-03 22:58 UTC, alfredo-dotcms commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/dot-container-contentlet.service.ts
> +        formId: string
fix doc

2022-02-04 15:46 UTC, fmontes requested changes

2022-02-04 17:43 UTC, hmoreras commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/dot-edit-content-html/dot-edit-content-html.service.ts
> +    renderAddedForm(formId: string, isDroppedAsset = false): Observable<DotPageContainer[]> {
that we need to find the placeholder and set the current container. When the form is selected from the form list, that is set already previously  .

2022-02-07 16:24 UTC, merged