dotCMS/core#21659 fix Invalidate localstorage messages keys when dotc…
dotCMS/core-web pull request #1875
Opened 2022-02-08 19:23 UTC by alfredo-dotcms

…ms updates

problem is that in new versions updates a message looks like is getting cached and not showing the proper label

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-02-08 19:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1875) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1875) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1875) it.</sub>

2022-02-08 20:17 UTC, fmontes requested changes

2022-02-08 20:17 UTC, fmontes commented on apps/dotcms-ui/src/app/app.component.ts
> +                    }
Can't we just do all this in the `dotMessageService`? Since we have an instance of `dotLocalstorageService` there as well.

2022-02-09 15:06 UTC, hmoreras approved these changes

2022-02-09 15:21 UTC, fmontes approved these changes

2022-02-09 16:14 UTC, merged