dotCMS/core#18019 fix Update dot-binary-file web component to support maxFileLength attr
dotCMS/core-web pull request #1917
Opened 2022-03-11 00:02 UTC by alfredo-dotcms

### Proposed Changes
In the dot-binary-file web component we have the property `maxFileLength` but we don't do anything with it.

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-03-11 00:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1917) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1917) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1917) it.</sub>

2022-03-11 00:03 UTC, alfredo-dotcms commented on libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-binary-file/dot-binary-file.tsx
> -                <dot-error-message>{this.errorMessage}</dot-error-message>
not used

2022-03-11 19:43 UTC, hmoreras requested changes

2022-03-11 19:43 UTC, hmoreras commented on libs/dotcms-webcomponents/src/components.d.ts
> +        /**
duplicate attr ?!

2022-03-11 21:32 UTC, hmoreras submitted a review, later dismissed

2022-03-14 03:51 UTC, fmontes requested changes

2022-03-14 03:51 UTC, fmontes commented on libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-binary-file/components/dot-binary-upload-button/dot-binary-upload-button.tsx
> +    @Prop({ reflect: true, mutable: true })
Why mutable?

2022-03-15 22:49 UTC, alfredo-dotcms commented on libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-binary-file/components/dot-binary-upload-button/dot-binary-upload-button.tsx
> +    @Prop({ reflect: true, mutable: true })
no reason

2022-03-16 19:49 UTC, hmoreras approved these changes

2022-03-24 16:33 UTC, fmontes approved these changes

2022-03-24 22:31 UTC, merged