dotCMS/core#19562 fix disabled on dot-key-values allowing to drag and…
dotCMS/core-web pull request #1942
Opened 2022-04-06 21:30 UTC by alfredo-dotcms

… drop

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-04-06 21:31 UTC, fmontes approved these changes

2022-04-06 21:45 UTC, fmontes requested changes

2022-04-06 21:45 UTC, fmontes commented on libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-key-value/components/key-value-table/key-value-table.tsx
> +        if (!this.disabled) {
Test?

2022-04-12 18:21 UTC, fmontes approved these changes

2022-04-12 20:04 UTC, hmoreras approved these changes

2022-04-12 20:04 UTC, merged