dotCMS/core#21839 Create content type modal needs some styling help to show the required license message Open
dotCMS/core-web pull request #1945
Opened 2022-04-07 22:20 UTC by hmoreras

### Proposed Changes
Fix: https://github.com/dotcms/core/issues/21839

2022-04-07 22:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1945) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1945) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1945) it.</sub>

2022-04-07 22:28 UTC, alfredo-dotcms approved these changes

2022-04-07 22:46 UTC, oidacra approved these changes

2022-04-08 12:56 UTC, fmontes requested changes

2022-04-08 12:56 UTC, fmontes commented on apps/dotcms-ui/src/app/portlets/shared/dot-content-types-edit/components/form/content-types-form.component.scss
> +    #field-workflow-hint {
Don't use id to styles.

2022-04-08 15:53 UTC, oidacra approved these changes

2022-04-08 17:08 UTC, merged