dotCMS/core#22140 Contentlet loosing in the page after layout change
dotCMS/core-web pull request #1972
Opened 2022-05-05 23:03 UTC by rjvelazco

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-05-05 23:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1972) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1972) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1972) it.</sub>

2022-05-06 13:13 UTC, hmoreras commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/layout/dot-edit-layout/dot-edit-layout.component.spec.ts
> +            // expect(dotPageLayoutService.save).toHaveBeenCalled();
remove

2022-05-06 13:15 UTC, hmoreras approved these changes

2022-05-06 13:39 UTC, alfredo-dotcms commented
@rjvelazco for some reason only 3 test were run

![image](https://user-images.githubusercontent.com/37185433/167144360-94c83936-177d-483a-b847-cb1eb08c38d4.png)

2022-05-06 13:43 UTC, rjvelazco commented
> @rjvelazco for some reason only 3 test were run
> 
> ![image](https://user-images.githubusercontent.com/37185433/167144360-94c83936-177d-483a-b847-cb1eb08c38d4.png)

2022-05-06 13:50 UTC, alfredo-dotcms approved these changes

2022-05-06 14:08 UTC, fmontes requested changes

2022-05-06 14:08 UTC, fmontes commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/layout/dot-edit-layout/dot-edit-layout.component.ts
> +                    error: (err: ResponseView) => this.handleErrorSaveTemplate(err)
Shouldn't this be in the subscribe?

2022-05-06 14:38 UTC, rjvelazco commented on apps/dotcms-ui/src/app/portlets/dot-edit-page/layout/dot-edit-layout/dot-edit-layout.component.ts
> +                    error: (err: ResponseView) => this.handleErrorSaveTemplate(err)
Right!

2022-05-06 15:09 UTC, oidacra approved these changes

2022-05-06 15:10 UTC, alfredo-dotcms approved these changes

2022-05-06 15:23 UTC, rjvelazco commented
> @rjvelazco for some reason only 3 test were run
> 
> ![image](https://user-images.githubusercontent.com/37185433/167144360-94c83936-177d-483a-b847-cb1eb08c38d4.png)

@alfredo-dotcms It looks like only those 3 tests have been running since this change was merged but, after the change, all tests passed! 😄

https://github.com/dotCMS/core-web/blob/b467060ed3e94d9e04c2559a5ce33ce91ff0d3f2/apps/dotcms-ui/src/app/view/components/_common/dot-inline-edit/dot-inline-edit.component.spec.ts#L31-L74

2022-05-06 15:26 UTC, fmontes approved these changes

2022-05-06 15:40 UTC, merged