dotCMS/core#22045 Filter contentlets in suggestions
dotCMS/core-web pull request #1973
Opened 2022-05-06 13:12 UTC by hmoreras

### Proposed Changes
* Allow the block editor to filter Content of specific Content Type. The results will show the first 40 maches.

2022-05-06 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1973) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1973) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1973) it.</sub>

2022-05-09 20:45 UTC, fmontes requested changes

2022-05-09 20:49 UTC, oidacra approved these changes

2022-05-09 21:00 UTC, fmontes approved these changes

2022-05-09 21:00 UTC, alfredo-dotcms approved these changes

2022-05-09 21:13 UTC, merged

2022-05-26 17:23 UTC, oidacra commented
In this issue, we need to fix an error of one subscription entered with these changes.

![Screen Shot 2022-05-26 at 12 21 32 PM](https://user-images.githubusercontent.com/1909643/170541505-8db15cb1-d228-4e80-b193-1135724406c9.png)

It's related to https://stackoverflow.com/a/67280960/12755139