dotCMS/core#22018 Paste images to create external images blocks
dotCMS/core-web pull request #1981
Opened 2022-05-11 22:54 UTC by rjvelazco

See how it works [here](https://www.loom.com/share/385172b6b3a24f8e92a31f8840780174)

2022-05-11 22:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core-web?pullRequest=1981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core-web?pullRequest=1981) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core-web?pullRequest=1981) it.</sub>

2022-05-12 14:24 UTC, hmoreras approved these changes

2022-05-12 16:33 UTC, fmontes requested changes

2022-05-12 18:12 UTC, rjvelazco commented on libs/block-editor/src/lib/utils/editor.utils.ts
> +export const insertNodeAt = ({ view, position, type, meta }: insertNodeAtProps) => {
Nice! Didn't know about that command!

2022-05-12 20:28 UTC, fmontes approved these changes

2022-05-12 21:29 UTC, merged